"""Abstract base strategy class."""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import List, Dict, Any
from data.models import OHLCV


@dataclass
class Signal:
    """Trading signal generated by a strategy."""

    symbol: str
    action: str  # BUY, SELL, HOLD
    confidence: float  # 0.0 to 1.0
    metadata: Dict[str, Any]

    def __post_init__(self) -> None:
        """Validate signal after initialization."""
        if self.action not in ("BUY", "SELL", "HOLD"):
            raise ValueError(f"Invalid action: {self.action}")
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be between 0 and 1: {self.confidence}")


class BaseStrategy(ABC):
    """
    Abstract base class for trading strategies.

    Strategies receive OHLCV data and generate trading signals.
    """

    @abstractmethod
    async def generate_signal(self, ohlcv_data: List[OHLCV]) -> Signal:
        """
        Generate trading signal based on OHLCV data.

        Args:
            ohlcv_data: List of OHLCV candlestick data

        Returns:
            Trading signal with action and confidence
        """
        pass
